* Minimalistic textual system monitor for plasma
** What is this?
This is a plasma widget which displays data emitted by the "systemmonitor" data
engine.  By default it shows
- total cpu load
- used application memory
- wlan down and up rate
- sda read and write rate

You most likely want to tweak the settings. This is done by editing the source
code. The settings dialog shows you how to get there.  This hacky way of
configuring the applet is no shortcoming but by intention. I wrote up a little
guide/tutorial on how to get stared with Javascript applets and how to tweak
TextMon.
 - [[http://maikbeckmann.github.com/plasma-textmon/]]
It isn't finished by any means, but IMO good enough to do more good than harm.

** What is plasma?
Plasma Workspaces is the umbrella term for all graphical environments provided
by KDE
 - [[http://en.wikipedia.org/wiki/KDE_Plasma_Workspaces][Wikipedia on Plasma]]
 - [[http://en.wikipedia.org/wiki/KDE_Software_Compilation_4][Wikipedia on KDE]]

Plasma is implemented as a framework which loads components.  A Component can
act as "data engine" or as an widget that visualizes such data.  It however
never does both.

Components are either native, which means they are written in C++, or they're
using one of the bindings to a dynamic language, like Python, Ruby and
Javascript.

The Javascript bindings are special as they're part of every plasma
installation and in that it's API is "simplified" aka. limited.  In return
components written with Javascript are ensured to be max. portable.

** A glimpse of awesomeness
This is also a tribute to the awesome window manager, where doing such a system
monitor widget is among the first things you learn. I've came to appreciate
knowing exactly when my system comes under pressure (cpu, mem, sda) or if a
download is still going (wlan).
